;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	copy-to-pasteboard
	cut-to-pasteboard
	ess-smart-comma
	ess-smarter-underscore
	ess-yank
	markdown-exdent-or-delete
	ns-paste-secondary
	paste-from-pasteboard
	))

(setq mc/cmds-to-run-once
      '(
	buffer-menu
	mouse-buffer-menu
	mouse-set-region
	simpleclip-cut
	suspend-frame
	))
