;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-kill-line
	beginning-of-visual-line
	copy-to-pasteboard
	cut-to-pasteboard
	end-of-visual-line
	ess-smart-comma
	ess-smarter-underscore
	ess-yank
	indent-for-tab-command
	mark-whole-word
	markdown-exdent-or-delete
	ns-paste-secondary
	org-self-insert-command
	outshine-self-insert-command
	paste-from-pasteboard
	simpleclip-paste
	))

(setq mc/cmds-to-run-once
      '(
	backward-kill-char-or-word
	beginning-of-buffer
	buffer-menu
	end-of-buffer
	ess-eval-region-or-line-and-step
	markdown-outdent-or-delete
	mouse-buffer-menu
	mouse-set-region
	org-cycle
	org-mouse-down-mouse
	polymode-export
	simpleclip-cut
	suspend-frame
	))
