;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	copy-to-pasteboard
	cut-to-pasteboard
	end-of-visual-line
	ess-smart-comma
	ess-smarter-underscore
	ess-yank
	indent-for-tab-command
	markdown-exdent-or-delete
	ns-paste-secondary
	org-self-insert-command
	outshine-self-insert-command
	paste-from-pasteboard
	simpleclip-paste
	))

(setq mc/cmds-to-run-once
      '(
	buffer-menu
	ess-eval-region-or-line-and-step
	mouse-buffer-menu
	mouse-set-region
	simpleclip-cut
	suspend-frame
	))
